
### Create Account
POST http://localhost:3000/accounts
Content-Type: application/json

{
  "name": "Fabricio",
  "cpf": "23123231219"
}
### FindAll
GET http://localhost:3000/accounts


### FindById
GET http://localhost:3000/accounts/1

### Update
PUT http://localhost:3000/accounts/1
Content-Type: application/json

{
  "nome": "Felipe",
  "cpf": "23118231219"
}

### Delete
DELETE http://localhost:3000/accounts/1

### Create Transaction -> Deposito
POST http://localhost:3000/transactions/deposit
Content-Type: application/json
{
  "transactionType": "deposit",
  "idAccount": 1,
  "amount": 500.00
}

### Create Transaction -> Transferência
POST http://localhost:3000/transactions/transfer
{
  "transactionType": "transfer",
  "idAccount": 1,
  "amount": 500.00,
  "idAccountTarget": 2
}

### FindAll
GET http://localhost:3000/transactions